### ISSUE TITLE
Install problems with python 3.7.3

### ISSUE THREAD

**Issue by andrzejnovak** [PierreBdR/PyQt-fit#1]
Seems to be a problem with installing distributed.

Error message below:
<details>
Collecting pyqt_fit
  Using cached https://files.pythonhosted.org/packages/bd/26/1679b81e3ca65aa955d91f57c2bd9fca7e05cb1b65bcc7d464961056e296/PyQt-Fit-1.4.0.tar.gz
Collecting distribute>=0.6
  Using cached https://files.pythonhosted.org/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip
    ERROR: Command errored out with exit status 1:
     command: /home/anovak/software/miniconda3/envs/def/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dbc9i624/distribute/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dbc9i624/distribute/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dbc9i624/distribute/pip-egg-info
         cwd: /tmp/pip-install-dbc9i624/distribute/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dbc9i624/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/pip-install-dbc9i624/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/pip-install-dbc9i624/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/tmp/pip-install-dbc9i624/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/pip-install-dbc9i624/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/pip-install-dbc9i624/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
</details>

**Comment by cpbl** [comment]
Yes, is this package dead? The readme suggests it should work with python 3 but I cannot install it under
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on Ubuntu 21.04.
I get an infinite loop of errors, like:

```

 python3 -m pip install --user pyqt-fit
Collecting pyqt-fit
  Using cached PyQt-Fit-1.4.0.tar.gz (104 kB)
  Preparing metadata (setup.py) ... done
Collecting distribute>=0.6
  Using cached distribute-0.7.3.zip (145 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b8aazjc2/distribute_7a610474e78b41babe0e2d32e5b359a6/setu
p.py'"'"'; __file__='"'"'/tmp/pip-install-b8aazjc2/distribute_7a610474e78b41babe0e2d32e5b359a6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os
.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(co
de, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ulbo2nn8
       cwd: /tmp/pip-install-b8aazjc2/distribute_7a610474e78b41babe0e2d32e5b359a6/
  Complete output (15 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-b8aazjc2/distribute_7a610474e78b41babe0e2d32e5b359a6/setuptools/__init__.py", line 2, in <module>
      from setuptools.extension import Extension, Library
    File "/tmp/pip-install-b8aazjc2/distribute_7a610474e78b41babe0e2d32e5b359a6/setuptools/extension.py", line 5, in <module>
      from setuptools.dist import _get_unpatched
    File "/tmp/pip-install-b8aazjc2/distribute_7a610474e78b41babe0e2d32e5b359a6/setuptools/dist.py", line 7, in <module>
      from setuptools.command.install import install
    File "/tmp/pip-install-b8aazjc2/distribute_7a610474e78b41babe0e2d32e5b359a6/setuptools/command/__init__.py", line 8, in <module>
      from setuptools.command import install_scripts
    File "/tmp/pip-install-b8aazjc2/distribute_7a610474e78b41babe0e2d32e5b359a6/setuptools/command/install_scripts.py", line 3, in <module>
      from pkg_resources import Distribution, PathMetadata, ensure_directory
    File "/tmp/pip-install-b8aazjc2/distribute_7a610474e78b41babe0e2d32e5b359a6/pkg_resources.py", line 1518, in <module>
      register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
  AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
  ---------------------------------------- 
WARNING: Discarding https://files.pythonhosted.org/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip#sha256=3dc7a8d059dcf
72f0ead2fa2144a24ee0ef07dce816e8c3545d7345767138c5e (from https://pypi.org/simple/distribute/). Command errored out with exit status 1: python setup.py egg_info Check t
he logs for full command output.
  Using cached distribute-0.6.49.zip (772 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:

```
and then it fails again with the cached version and keeps repeating.

**Comment by michaelcroquette** [comment]
Hello,

This module uses cython so you need a C++ compiler. If you follow the instruction on this link([https://wiki.python.org/moin/WindowsCompilers]) you should be able to go past that error and import the module with pip. 
I've gone with Microsoft Visual C++ but I still get an error after that when importing pyqt_fit  : 

`CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2`

I'm curious if you have the same error.
